# Generated by Django 5.2.1 on 2025-06-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_expcted_attendees_event_expected_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
