# Generated by Django 5.2.1 on 2025-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='expected_attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='expected_community',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='expected_faculty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='expected_others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='expected_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
