CREATE TABLE IF NOT EXISTS BUDGET_TABLE (
    Budget_ID INTEGER PRIMARY KEY,
    Item_Name VARCHAR(100),
    Item_Quantity INTEGER,
    Item_Cost DECIMAL(10, 2),
    Total_Cost DECIMAL(10, 2),
    Budget_Status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS EVENT_TABLE (
    Event_ID INTEGER PRIMARY KEY,
    Event_Name VARCHAR(100),
    Venue VARCHAR(100),
    Event_Start_Time TIME,
    Event_End_Time TIME,
    Event_Start_Date DATE,
    Event_End_Date DATE,
    Event_Location VARCHAR(100),
    Available_Seats INTEGER,
    Event_Status VARCHAR(50),
    Event_Description TEXT,
    Budget_ID INTEGER,
    Event_Host VARCHAR(100),
    FOREIGN KEY (Budget_ID) REFERENCES BUDGET_TABLE(Budget_ID)
);

CREATE TABLE IF NOT EXISTS USER_TABLE (
    User_ID INTEGER PRIMARY KEY,
    User_First_Name VARCHAR(50),
    User_Last_Name VARCHAR(50),
    User_Department VARCHAR(100),
    User_Role VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MEDIA_TABLE (
    Media_ID INTEGER PRIMARY KEY,
    Media_URL TEXT,
    Media_Type VARCHAR(50),
    Media_Name VARCHAR(100),
    User_ID INTEGER REFERENCES USER_TABLE(User_ID),
    Media_Size INTEGER
);

CREATE TABLE IF NOT EXISTS TAGS_CREATIONS_TABLE (
    Tag_ID INTEGER PRIMARY KEY,
    Tag_Name VARCHAR(100),
    Tag_Description TEXT
);

CREATE TABLE IF NOT EXISTS PERMISSIONS_TABLE (
    Permission_Name VARCHAR(100),
    Permission_Description TEXT
);

CREATE TABLE IF NOT EXISTS USER_EVENT_TABLE (
    User_ID INTEGER,
    Event_ID INTEGER,
    FOREIGN KEY (User_ID) REFERENCES USER_TABLE(User_ID),
    FOREIGN KEY (Event_ID) REFERENCES EVENT_TABLE(Event_ID)
);

CREATE TABLE IF NOT EXISTS EVENT_TAGS_TABLE (
    Event_ID INTEGER,
    Tag_ID INTEGER,
    FOREIGN KEY (Event_ID) REFERENCES EVENT_TABLE(Event_ID),
    FOREIGN KEY (Tag_ID) REFERENCES TAGS_CREATIONS_TABLE(Tag_ID)
);