DROP TABLE IF EXISTS EVENT_TABLE;
DROP TABLE IF EXISTS MEDIA_TABLE;
DROP TABLE IF EXISTS USER_TABLE;
DROP TABLE IF EXISTS BUDGET_TABLE;
DROP TABLE IF EXISTS TAGS_CREATIONS_TABLE;
DROP TABLE IF EXISTS PERMISSIONS_TABLE;
DROP TABLE IF EXISTS USER_EVENT_TABLE;