SELECT * FROM EVENT_TABLE;
SELECT * FROM USER_TABLE;
SELECT * FROM MEDIA_TABLE;
SELECT * FROM BUDGET_TABLE;
SELECT * FROM TAGS_CREATIONS_TABLE;
SELECT * FROM PERMISSIONS_TABLE;
SELECT * FROM USER_EVENT_TABLE;
SELECT * FROM EVENT_TAGS_TABLE;