# Generated by Django 5.2.1 on 2025-06-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permission_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permissionlevel')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionLevelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permissionlevel')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permissiontype')),
            ],
            options={
                'unique_together': {('permission_level', 'permission_type')},
            },
        ),
    ]
